// <auto-generated />
using System;
using FareEngine.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FareEngine.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260409102640_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FareEngine.Domain.FarePolicies.FarePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FarePolicies", (string)null);

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FareEngine.Domain.Modifications.Modification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Modifications", (string)null);

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FareEngine.Domain.SoldProducts.SoldProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SoldProducts", (string)null);

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FareEngine.Domain.FarePolicies.DistanceBasedFarePolicy", b =>
                {
                    b.HasBaseType("FareEngine.Domain.FarePolicies.FarePolicy");

                    b.Property<decimal>("RatePerKm")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("FareEngine.Domain.FarePolicies.FlatRateFarePolicy", b =>
                {
                    b.HasBaseType("FareEngine.Domain.FarePolicies.FarePolicy");

                    b.Property<decimal>("FlatAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("FareEngine.Domain.FarePolicies.ZoneBasedFarePolicy", b =>
                {
                    b.HasBaseType("FareEngine.Domain.FarePolicies.FarePolicy");

                    b.Property<int>("ZoneNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("ZonePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("FareEngine.Domain.Modifications.FirstClassModification", b =>
                {
                    b.HasBaseType("FareEngine.Domain.Modifications.Modification");

                    b.Property<decimal>("Surcharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("FareEngine.Domain.Modifications.SeniorDiscountModification", b =>
                {
                    b.HasBaseType("FareEngine.Domain.Modifications.Modification");

                    b.Property<decimal>("DiscountPercentage")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("FareEngine.Domain.SoldProducts.SoldDailyPass", b =>
                {
                    b.HasBaseType("FareEngine.Domain.SoldProducts.SoldProduct");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("FareEngine.Domain.SoldProducts.SoldHybridTrip", b =>
                {
                    b.HasBaseType("FareEngine.Domain.SoldProducts.SoldProduct");

                    b.Property<decimal>("DistanceInKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ZoneNumber")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("FareEngine.Domain.SoldProducts.SoldProduct", b =>
                {
                    b.OwnsMany("FareEngine.Domain.SoldProducts.SoldProductFarePolicy", "FarePolicies", b1 =>
                        {
                            b1.Property<Guid>("SoldProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("FarePolicyId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("SoldProductId", "Id");

                            b1.ToTable("SoldProductFarePolicy");

                            b1.WithOwner()
                                .HasForeignKey("SoldProductId");
                        });

                    b.OwnsMany("FareEngine.Domain.SoldProducts.SoldProductModification", "Modifications", b1 =>
                        {
                            b1.Property<Guid>("SoldProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("ModificationId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("SoldProductId", "Id");

                            b1.ToTable("SoldProductModification");

                            b1.WithOwner()
                                .HasForeignKey("SoldProductId");
                        });

                    b.Navigation("FarePolicies");

                    b.Navigation("Modifications");
                });
#pragma warning restore 612, 618
        }
    }
}
